// Array of students' games
export const games = [
    {
      title: `Ballard's Birds`,
      author: `Dominguez`,
      description: `Ballard's Birds is a platformer game that puts you in control of the fearless Mr. Ballard. Help him destroy flocks of birds, grab some jambalaya, and rescue sweet Rosie.`,
      link: `https://makecode.com/_YWXdPbRmMCyj`,
      image: `images/bbgif.gif`,
      protagonist: `Mr. Ballard`,
      genre: `Platformer`,
      term: `Fall 2020`,
    },
    {
      title: `Turkey Trot`,
      author: `Bennettt M.`,
      description: `Help the turkey find his way through the maze and past the obstacles. Before you know it, he'll be gobbling for victory at the end of the map!`,
      link: `https://makecode.com/_CALCuVach2Uz`,
      image: `images/gobbles.gif`,
      protagonist: `Gobbles`,
      genre: `Action-adventure`,
      term: `Fall 2020`,
    },
    {
      title: `Wizard Vs. Witches`,
      author: `Zahid I.`,
      description: `Help Merlin get to the big chest at the other side that is guarded by snakes, bats, and witches. Make sure to collect tiny chests on the way to get points. Watch out there are many booby traps!`,
      link: `https://makecode.com/_TFmYtHRwK2Kc`,
      image: `images/Merlin.gif`,
      protagonist: `Merlin`,
      genre: `Action-adventure`,
      term: `Fall 2020`,
    },
  ];
  title: `Messi Soccer`,
      author: `Abbey S.`,
      description: `Get Messi to the Golden Goal without getting destroyed by Ronaldo. Collect the soccer balls for points.`,
      link: `https://makecode.com/_JDVRJ9W6mXLv`,
      image: `images/Messi.gif`,
      protagonist: `Messi`,
      genre: `Sports-Adventure`,
      term: `Fall 2020`,
    },
  ];
